#! /bin/bash
#
# /etc/init.d/rosstart
#
# Author:
#	Biel Piero Alvarado Vasquez <biel.piero@gmail.com>
#
### BEGIN INIT INFO
# Provides:		rosstart
# Required-Start:	$local_fs $remote_fs $network
# Required-Stop:
# Should-Start:		$named
# Should-Stop:		$named
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Starts ROBOT kernel Applications.
# Description: Starts ROS core services, and other applications.
### END INIT INFO

#source /opt/ros/hydro/setup.bash
#source /home/doris/catkin_ws/devel/setup.bash

#export ROS_HOSTNAME=ros_machine
#export ROS_IP=192.168.1.101
#export ROS_MAIN_URI=http://ros_machine:11311

sudo modprobe em28xx card=9
sudo echo 1b80 e600 > /sys/bus/usb/drivers/em28xx/new_id

sudo chmod a+rw -R /dev/video0
sudo chmod a+rw -R /dev/video1
sudo chmod a+rw -R /dev/video2
sudo chmod 777 /dev/ttyS2
stty -F /dev/ttyS0 115200
stty -F /dev/ttyS1 115200
stty -F /dev/ttyS2 115200
stty -F /dev/ttyS3 115200

sudo rmmod ftdi_sio
sudo rmmod usbserial

#roscore&
#sleep 5

echo 3 > /proc/sys/vm/drop_caches

#rosrun lucky_bea lucky_bea&

exit 0
