#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define REGEX_STR "[a-zA-Z_$][a-zA-Z_$0-9]*"

#define TOK_TRUE "NUM:1"
#define TOK_FALSE "NUM:0"

#define EVENT_ON_RFID_TAGS_DETECTED_STR "onRfidTagsDetected"
#define EVENT_ON_SECTOR_CHANGED_STR "onSectorChanged"

#define NULLPTR "UNK:nil"

#define RW_FUNCTION_STR "function"
#define RW_END_FUNCTION_STR "endfunction"
#define RW_IF_STR "if"
#define RW_ELSE_STR "else"
#define RW_ENDIF_STR "endif"
#define RW_WHILE_STR "while"
#define RW_ENDWHILE_STR "endw"
#define RW_MOVE_STR "move"
#define RW_GOTO_STR "goto"
#define RW_SAY_STR "say"
#define RW_TURN_STR "turn"
#define RW_ATTENTION_STR "attention"
#define RW_VAR_STR "var"
#define RW_RETURN_STR "return"
#define RW_AND_STR "and"
#define RW_OR_STR "or"
#define RW_NOT_STR "not"
#define RW_FACE_STR "face"
#define RW_FOR_STR "for"
#define RW_ENDFOR_STR "endfor"
#define RW_SIZEOF_STR "sizeof"
#define RW_WAIT_STR "wait"

#define TOK_SIZEOF_STR "SIZEOF"
#define TOK_IF_STR "IF"
#define TOK_WHILE_STR "WHILE"
#define TOK_FOR_STR "FOR"
#define TOK_MOVE_STR "MOVE"
#define TOK_GOTO_STR "GOTO"
#define TOK_SAY_STR "SAY"
#define TOK_TURN_STR "TURN"
#define TOK_ATTENTION_STR "ATTENTION"
#define TOK_RETURN_STR "RETURN"
#define TOK_WAIT_STR "WAIT"
#define TOK_DVR2PTS_STR "DVR:"
#define TOK_NUM2PTS_STR "NUM:"
#define TOK_ARG2PTS_STR "ARG:"
#define TOK_VAR2PTS_STR "VAR:"
#define TOK_EXP2PTS_STR "EXP:"
#define TOK_FNC2PTS_STR "FNC:"
#define TOK_EFC2PTS_STR "EFC:"
#define TOK_STR2PTS_STR "STR:"
#define TOK_EQ_STR "EQ"
#define TOK_BIF2PTS_STR "BIF:"
#define TOK_BEL2PTS_STR "BEL:"
#define TOK_EIF2PTS_STR "EIF:"
#define TOK_BWH2PTS_STR "BWH:"
#define TOK_BFOR2PTS_STR "BFOR:"
#define TOK_EFOR2PTS_STR "EFOR:"
#define TOK_EWH2PTS_STR "EWH:"
#define TOK_OPT2PTS_STR "OPT:"
#define TOK_FACE2PTS_STR "FACE:"
#define TOK_ATTN2PTS_STR "ATTN:"
#define TOK_ARR2PTS_STR "ARR:"
#define TOK_POS2PTS_STR "POS:"
#define TOK_ARR_STR "ARR"
#define TOK_POS_STR "POS"
#define TOK_STR_STR "STR"
#define TOK_VAR_STR "VAR"
#define TOK_NUM_STR "NUM"
#define TOK_TURN_STR "TURN"
#define TOK_FNC_STR "FNC"
#define TOK_EFC_STR "EFC"
#define TOK_OPT_STR "OPT"
#define TOK_ARG_STR "ARG"
#define TOK_DVR_STR "DVR"
#define TOK_EXP_STR "EXP"
#define TOK_BEL_STR "BEL"
#define TOK_EIF_STR "EIF"
#define TOK_EWH_STR "EWH"
#define TOK_EFOR_STR "EFOR"
#define TOK_VOID_STR "VOID"
#define TOK_AND_STR "AND"
#define TOK_OR_STR "OR"
#define TOK_EQU_STR "EQU"
#define TOK_NEQ_STR "NEQ"
#define TOK_LT_STR "LT"
#define TOK_LEQ_STR "LEQ"
#define TOK_GT_STR "GT"
#define TOK_GEQ_STR "GEQ"
#define TOK_NOT_STR "NOT"
#endif