#define XML_STATIC_GESTURES_STR "GestosEstaticos"
#define XML_DYNAMIC_GESTURES_STR "GestosDinamicos"

#define XML_ATTRIBUTE_ID_STR "id"
#define XML_ATTRIBUTE_CARD_ID_STR "cardId"
#define XML_ATTRIBUTE_POSITION_STR "pos"
#define XML_ATTRIBUTE_SPEED_STR "speed"
#define XML_ATTRIBUTE_ACCELERATION_STR "acceleration"
#define XML_ATTRIBUTE_TYPE_STR "tipo"
#define XML_ATTRIBUTE_NAME_STR "name"

#define XML_ELEMENT_GESTURE_STR "Gesto"
#define XML_ELEMENT_MOTOR_STR "Motor"

#define XML_ELEMENT_MAPS_STR "maps"
#define XML_ELEMENT_MAP_STR "map"

#define XML_ATTRIBUTE_FILENAME_STR "filename"
#define XML_ATTRIBUTE_POLYGON_STR "polygon"

#define XML_ELEMENT_SECTORS_STR "sectors"
#define XML_ELEMENT_SECTOR_STR "sector"
#define XML_ELEMENT_LANDMARKS_STR "landmarks"
#define XML_ELEMENT_LANDMARK_STR "landmark"
#define XML_ELEMENT_FEATURES_STR "features"
#define XML_ELEMENT_FEATURE_STR "feature"
#define XML_ELEMENT_SITES_STR "sites"
#define XML_ELEMENT_SITE_STR "site"

#define XML_ELEMENT_PERMISSIONS_STR "permissions"
#define XML_ELEMENT_PERMISSION_STR "permission"

#define XML_ATTRIBUTE_FUNCTION_STR "function"
#define XML_ATTRIBUTE_TOKEN_REQUIRED_STR "token-required"

#define XML_ELEMENT_ROBOT_STR "robot"
#define XML_ELEMENT_NAV_PARAMS_STR "navigation-params"
#define XML_ELEMENT_INITIAL_POS_STR "initial-position"
#define XML_ELEMENT_PROCESS_NOISE_STR "process-noise"
#define XML_ELEMENT_OBSERV_NOISE_STR "observation-noise"
#define XML_ELEMENT_POS_X_ZONE_STR "x-zone"
#define XML_ELEMENT_POS_Y_ZONE_STR "y-zone"
#define XML_ELEMENT_POS_TH_ZONE_STR "th-zone"
#define XML_ELEMENT_POS_D_ZONE_STR "d-zone"

#define XML_ATTRIBUTE_CYCLIC_STR "cyclic"
#define XML_ATTRIBUTE_SEQUENCE_STR "sequence"
#define XML_ATTRIBUTE_VARIANCE_STR "var"
#define XML_ATTRIBUTE_VARIANCE_MIN_X_STR "var-min-x"
#define XML_ATTRIBUTE_VARIANCE_MAX_X_STR "var-max-x"
#define XML_ATTRIBUTE_VARIANCE_MIN_Y_STR "var-min-y"
#define XML_ATTRIBUTE_VARIANCE_MAX_Y_STR "var-max-y"
#define XML_ATTRIBUTE_WIDTH_STR "width"
#define XML_ATTRIBUTE_HEIGHT_STR "height"
#define XML_ATTRIBUTE_RADIUS_STR "radius"
#define XML_ATTRIBUTE_TIME_STR "tsec"
#define XML_ATTRIBUTE_X_POSITION_STR "xpos"
#define XML_ATTRIBUTE_Y_POSITION_STR "ypos"
#define XML_ATTRIBUTE_LINKED_FEATURE_ID_STR "linked-feature-id"
#define XML_ATTRIBUTE_LINKED_SECTOR_ID_STR "linked-sector-id"
#define XML_ATTRIBUTE_REFERENCE_STR "reference"

#define XML_ATTRIBUTE_ALPHA_STR "alpha"
#define XML_ATTRIBUTE_TRAP_X1_STR "x1"
#define XML_ATTRIBUTE_TRAP_X2_STR "x2"
#define XML_ATTRIBUTE_TRAP_X3_STR "x3"
#define XML_ATTRIBUTE_TRAP_X4_STR "x4"
