#define XML_STATIC_GESTURES_STR "GestosEstaticos"
#define XML_DYNAMIC_GESTURES_STR "GestosDinamicos"

#define XML_ATTRIBUTE_ID_STR "id"
#define XML_ATTRIBUTE_CARD_ID_STR "cardId"
#define XML_ATTRIBUTE_POSITION_STR "pos"
#define XML_ATTRIBUTE_SPEED_STR "speed"
#define XML_ATTRIBUTE_ACCELERATION_STR "acceleration"
#define XML_ATTRIBUTE_TYPE_STR "tipo"
#define XML_ATTRIBUTE_NAME_STR "name"

#define XML_ELEMENT_GESTURE_STR "Gesto"
#define XML_ELEMENT_MOTOR_STR "Motor"

#define XML_ELEMENT_SECTORS_STR "sectors"
#define XML_ELEMENT_SECTOR_STR "sector"
#define XML_ELEMENT_LANDMARKS_STR "landmarks"
#define XML_ELEMENT_LANDMARK_STR "landmark"
#define XML_ELEMENT_FEATURES_STR "features"
#define XML_ELEMENT_FEATURE_STR "feature"
#define XML_ELEMENT_SITES_STR "sites"
#define XML_ELEMENT_SITE_STR "site"

#define XML_ATTRIBUTE_VARIANCE_STR "var"
#define XML_ATTRIBUTE_WIDTH_STR "width"
#define XML_ATTRIBUTE_HEIGHT_STR "height"
#define XML_ATTRIBUTE_TIME_STR "tsec"
#define XML_ATTRIBUTE_X_POSITION_STR "xpos"
#define XML_ATTRIBUTE_Y_POSITION_STR "ypos"